on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  quality:
    uses: isinghabhishek/.github/.github/workflows/code-quality.yml@main
    with:
      run-clippy: true
      run-fmt: true
      run-test: false
